name: vrchat_dart_example
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  vrchat_dart:
    path: ../

  otp: ^3.1.3

dev_dependencies:
  rexios_lints: ^7.0.0

dependency_overrides:
  vrchat_dart_generated:
    path: ../../vrchat_dart_generated
