name: Generate

on:
  repository_dispatch:
    types: [spec_release]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Pub cache
        uses: actions/cache@v4
        env:
          cache-name: root
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ env.cache-name }}-

      - name: Homebrew cache
        uses: actions/cache@v4
        with:
          path: |
            /home/linuxbrew/.linuxbrew
            /home/linuxbrew/.linuxbrew/Library/Taps
            /home/linuxbrew/.cache/Homebrew
            /home/linuxbrew/.linuxbrew/Cellar
            /home/linuxbrew/.linuxbrew/bin/brew
          key: ${{ runner.os }}-brew-${{ hashFiles('**/Brewfile') }}
          restore-keys: |
            ${{ runner.os }}-brew-

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Generate
        run: ./generate.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ci/regenerate-from-spec
          commit-message: "Regenerated from spec"
          title: "[CI] Regenerated from spec"
          body: "Regenerated from spec"
