name: Major Dependency Upgrades

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  upgrade-dependencies:
    runs-on: ubuntu-latest
    container:
      image: dart:latest
    steps:
      - uses: actions/checkout@v4

      - name: Pub cache
        uses: actions/cache@v4
        with:
          path: .pub-cache
          key: pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: pub-cache-

      - name: Activate puby
        run: dart pub global activate puby

      - name: Upgrade dependencies
        run: puby upgrade --major-versions

      - name: Check pubspec diff
        id: pubspec_check
        run: |
          if [[ `git status --porcelain **\pubspec.yaml` ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Create Pull Request
        if: steps.pubspec_check.outputs.changed
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ci/major-dependency-upgrades
          commit-message: "Upgraded dependency major versions"
          title: "[CI] Major Dependency Upgrades"
          body: "Upgraded dependency major versions"
